Given customer information from a credit card dataset, predict a customer’s credit card balance using statistical learning methods.

In [2]:
!pip install ISLP
import numpy as np
import pandas as pd
from ISLP import load_data


df = load_data('Credit')

print(df.head())

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 68.7 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.3/349.3 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.5/849.5 kB 42.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 33.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 10.1 MB/s eta 0:00:00
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=7215f8929a0e75e94b0e746649e320b1e89a6218bd968c2a6bab077c0401fab4
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
   ID   Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   1   14.891   3606     283      2   34         11    Male      No     Yes   
1   2  1

In [3]:
df.info

<bound method DataFrame.info of       ID   Income  Limit  Rating  Cards  Age  Education  Gender Student  \
0      1   14.891   3606     283      2   34         11    Male      No   
1      2  106.025   6645     483      3   82         15  Female     Yes   
2      3  104.593   7075     514      4   71         11    Male      No   
3      4  148.924   9504     681      3   36         11  Female      No   
4      5   55.882   4897     357      2   68         16    Male      No   
..   ...      ...    ...     ...    ...  ...        ...     ...     ...   
395  396   12.096   4100     307      3   32         13    Male      No   
396  397   13.364   3838     296      5   65         17    Male      No   
397  398   57.872   4171     321      5   67         12  Female      No   
398  399   37.728   2525     192      1   44         13    Male      No   
399  400   18.701   5524     415      5   64          7  Female      No   

    Married         Ethnicity  Balance  
0       Yes         Caucas

In [7]:
X = df[['Income', 'Limit', 'Rating', 'Cards', 'Age']].values
y = df['Balance']

print(X)

[[1.48910e+01 3.60600e+03 2.83000e+02 2.00000e+00 3.40000e+01]
 [1.06025e+02 6.64500e+03 4.83000e+02 3.00000e+00 8.20000e+01]
 [1.04593e+02 7.07500e+03 5.14000e+02 4.00000e+00 7.10000e+01]
 ...
 [5.78720e+01 4.17100e+03 3.21000e+02 5.00000e+00 6.70000e+01]
 [3.77280e+01 2.52500e+03 1.92000e+02 1.00000e+00 4.40000e+01]
 [1.87010e+01 5.52400e+03 4.15000e+02 5.00000e+00 6.40000e+01]]


In [28]:
np.random.seed(11)
indices = np.random.permutation(X.shape[0])
split = int(0.75 * X.shape[0])

In [29]:
train_idx, test_idx = indices[:split], indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

X_mean = X_train.mean(axis=0)
X_std  = X_train.std(axis=0)


In [30]:
X_train_scaled = (X_train - X_mean) / X_std
X_test_scaled  = (X_test  - X_mean) / X_std


/tmp/ipython-input-2083823792.py:1: RuntimeWarning: invalid value encountered in divide
  X_train_scaled = (X_train - X_mean) / X_std
/tmp/ipython-input-2083823792.py:2: RuntimeWarning: invalid value encountered in divide
  X_test_scaled  = (X_test  - X_mean) / X_std


In [31]:

X_train_b = np.c_[np.ones(X_train_scaled.shape[0]), X_train_scaled]
X_test_b  = np.c_[np.ones(X_test_scaled.shape[0]),  X_test_scaled]

In [32]:
#linear regression

theta = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train


In [33]:
y_prediction = X_test @ theta

In [34]:
mse = np.mean((y_test - y_prediction) ** 2)

In [35]:
print ( f"learned parameters: theta = {theta}")

print(f"MSE: {mse}")

learned parameters: theta = [-4.52744876e+02 -7.26476520e+00  1.03801807e-01  2.33284525e+00
  1.37165650e+01 -1.02837585e+00]
MSE: 29066.85166520737
